name: ChatCommando-Plugin
main: chatcommandoplugin
version: 1.0
commands:
  halloserver:
    description: Sendet einen Gruss an den Server
    usage: /halloserver
  eierkuchen:
    description: Sendet einen Eierkuchen an den Spieler
    usage: /eierkuchen